// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js usa .env.local; o CLI do Prisma só carregava .env (senha antiga → P1000).
loadEnv({ path: ".env" });
loadEnv({ path: ".env.local", override: true });

/** CLI (db push): prefira DIRECT_URL — use Session pooler se db.* só tiver IPv6 (P1001 no Windows). */
function pickPrismaDatasourceUrl(): string {
  return (
    process.env["DIRECT_URL"] ??
    process.env["POSTGRES_URL_NON_POOLING"] ??
    process.env["DATABASE_URL"] ??
    process.env["POSTGRES_PRISMA_URL"] ??
    process.env["POSTGRES_URL"] ??
    ""
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed-runner.cjs",
  },
  datasource: {
    url: pickPrismaDatasourceUrl(),
  },
});
